### ISSUE TITLE
Dot plot marker sizes may need to be checked in both horizontal and vertical dimensions

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#161]
I'm guessing our dot plot marker size calculator only cares about the height of the viewer?

The angular size is more broadly distributed across multiple values, so they are large and running into each other. Please fix if it would be fast, but not at expense of more critical issues.
<img width="1129" alt="Screen Shot 2023-04-25 at 5 29 02 PM" src="https://user-images.githubusercontent.com/12750048/234409191-28d769c4-b58e-42a1-8dfa-3411dedb7b9a.png">

**Comment by Carifio24** [comment]
Yeah, only the vertical dimension (viewer y-range and height) are considered when making the size determination. We could find the relevant size based on the width and number of bins, and then just take the smaller of those two. I can try that out and see how it works.

**Comment by Carifio24** [comment]
So this was a bit trickier than I was originally expecting, because the viewers currently don't know their own pixel width.

I've got a PR in cosmicds (https://github.com/cosmicds/cosmicds/pull/217) which gives the CosmicDS viewer states the ability to know their size. That PR also uses that knowledge to calculate the dot size based on both x- and y-dimensions.
