### ISSUE TITLE
Free-responses entered by students do not persist in guidelines during session

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#278]
If I type a free response into guidelines like Stage 5 con_int2c (or mos_lik4 or con_int3), then back up to a previous guideline, when I return to that guideline, my responses do not persist and I have to type them all in again.

@Carifio24, didn't we fix this at some point? Or is there a particular thing we need to do to "lock in" responses that we haven't implemented here?

**Comment by johnarban** [comment]
So I was getting an issue with the best guess age, here the issue was the free response had the wrong tag (`most-likely-age` instead of `best-guess-age`. I am slowly making it through the stage, making minor changes, and trying to catch mismatches. keeping as many old variable names the same as possible (so long as the value being assigned to it has the same meaning) i think will preserve backwards compatibility. Of course, if something is truly new, a new state variable is fine.

**Comment by patudom** [comment]
Thanks, @johnarban. I just checked with @Carifio24, and he said that we should be able to change the tag to whatever we want, and as long as a student has always used a version of the app with a particular tag, it should persist. (I did try changing the tag back to `best-guess-age` and it did not solve the issue). I'm pretty sure Jon had fixed this issue in the past, but something seems to have "unfixed" it, so Jon said he'd take a look.

**Comment by johnarban** [comment]
Well it fixed the problem I was having. This issue was that `state.age_calc_state.best_guess` get's set in a function `age_cal_update_guesses` which looks specifically for the `best-guess-age` tag, and so the state variable was never being updated with the age. 914ec7a09623780cdbf48f5b8c03402d7a270ca9 fixes this particular issue.

**Comment by Carifio24** [comment]
Ok yeah, in this case (and for some of those nested state dicts) the tag does matter, since it's referenced outside of the FR itself.

**Comment by patudom** [comment]
Yes, there are 2 different situations where we need those student entries to persist.

- There are places where we refer in future guidelines to the student's entered text, and those definitely need to have matching tags. @johnarban, let me know if you have a branch going where you're matching up those tags with what's in the state. If not, I can work on that before tomorrow.
<img width="475" alt="Screen Shot 2023-07-18 at 12 19 20 PM" src="https://github.com/cosmicds/hubbleds/assets/12750048/5160b9c3-f2b8-4a13-996d-0556c9a1df49">

- We also need for their responses to remain within the boxes where they first entered them (for example, if they move forward and then backtrack to that guideline, their entries need to persist, and the app needs to let them proceed without having to retype their responses). This is the piece that Jon was referring to that should happen automatically without our having to do anything, and in my most recent testing it seems ok. I think where it seemed like it wasn't working to me before was from the notebook caching causing problems. 🤞 
<img width="921" alt="Screen Shot 2023-07-18 at 12 23 52 PM" src="https://github.com/cosmicds/hubbleds/assets/12750048/186d2215-43b7-437c-a05f-39000b9d187a">

**Comment by patudom** [comment]
This is behaving as desired on the AWS server and locally on voila. I'm going to chalk this up to an issue caused by aggressive caching when we're in the notebook.
