### ISSUE TITLE
Class data between student sessions

### ISSUE THREAD

**Issue by Carifio24** [cosmicds/hubbleds#284]
Currently, when a student reaches stage 5, we "freeze" the class data that the student sees (by just no longer querying the database for class data updates). This provides a more consistent experience for the student - the data isn't changing as they're trying to ask questions about this.

However, this is purely a client-side effect at this point - there's nothing saved in the database that reflects the state of the student's class data. This means that if a student reloads the story (either because they're doing the story across multiple classroom sessions, or they just had to refresh the browser page), the class data in stage 5 could potentially change from what they had previously seen.

There are two approaches to this:
- We're fine with this. The students will be aware that their classmates are still collecting data (maybe we add something reminding them of this?), and will understand that the data set may change.
- We retain the "class data" information specific to that student. This wouldn't be difficult to do - one implementation could be to store the student IDs whose data was used inside the story state (which is saved to the database). Then, when the class data is fetched when the story starts, we can just drop any data where the student ID wasn't used previously.

I don't know that I have a preference for this yet - if anyone has any thoughts, please share here.

**Comment by patudom** [comment]
Approach for handling changing numbers of available datasets midway through a class’s implementation:

- Once a student gets to Stage 4, turn off their ability to edit their measurements (because if they can change them, that makes everyone’s data set slosh around in confusing ways that are a pain to account for).
- First time student starts story - create an “ALL DATA” timestamp for them.
- Every subsequent time they logon, we only load data ALL STUDENTS and ALL CLASSES created from before that time.
- When a student gets to Stage 5, count how many kids are in their class (since this value is not known for classes joining with a classroom code).
- For the students who get to stage 5 first, whichever other kids are finished, 
  - get a list of their student IDs and store those. So the next time you come back, you only retain those students. (Drop rows that don’t match the ID list).
  - Add "MY CLASS" to the "ALL CLASSES" dataset locally using the "MY CLASS" data available at this time.
  - Store in student’s state for teacher: basic stats for that dataset
    - Mean/Median/Mode
    - 50/68/95% ranges

**Comment by patudom** [comment]
Small Class Handling:

- Assume the threshold is <= 12 to declare it a small class.
- The first student who gets to Stage 4 is the "trigger" for determining whether a class is small. At that point, count how many students have logged on with the classroom code, and that is the N. If it's a small N, then even if more students join later, they are being handled as a small class.
- For a small class, there is no "Wait" period because everyone's data that is available gets automatically merged with a prior class.


- [ ] Keep pondering this one. Edge case if there is a 13-person class where there aren't 10 kids who have finished making galaxy measurements on Day 1 and then 4 kids are absent the next day. In that case, they'll never make it to 10 students and no one can advance.

Possible options

- Provide a "time out" feature where if a kid has been waiting for too long, we pop up a message to ask the teacher to check how everyone is doing; if they are not going to be able to meet the conditions to proceed, the teacher can do an override from their dashboard. Or we can just put a guideline that says to ask teacher for permission to proceed and then they can just hit next.

**Comment by Carifio24** [comment]
Just leaving a note that, rather than drop measurements from students that aren't in the "class data students" list, I figured it would be easier to do this filtering inside the API server.
