### ISSUE TITLE
remaining WWT issues in solara update

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#346]
- [x] remove chrome (set so it doesn't appear by default then disappear)
- [x] use SDSS as background for stages 1 & 3
- [x] SDSS galaxy table in Stage 1 only seems to load the first time a user accesses the solara app. If a user didn't select all 5 of their galaxies on that first load, there is no way for them to add to their dataset.

**Comment by johnarban** [comment]
These should be fixed on https://github.com/nmearl/hubbleds/pull/1 in conjunction with https://github.com/nmearl/ipywwt/pull/4 on @nmearl's branch

**Comment by Carifio24** [comment]
In my testing this all worked well, I didn't see any issues. The only concern that I have is whether or not it's possible for the message from the `mounted` hook to be emitted before the Python handler is set up. My hunch is that this won't happen, but I couldn't convince myself that it's impossible.

I might try and set up a ping-pong message based version of this, mostly since the fewer deviations we have from the upstream research app the easier the easier this will be to integrate later on. But I think this is fine for now.
